### ISSUE TITLE
我在看你的gitbook，提个意见

### ISSUE THREAD

**Issue by Insofan** [gavinfish/leetcode-share#1]
005最长回文子字符串,应该用Manacher Algorithm（马拉车算法），能从O(n^2)提高到O(n)。我也不太会算法在慢慢做题而已，只是自己在慢慢研究，谢谢你的书。
相关资料
http://www.jianshu.com/p/799bc53d4e3d
https://www.youtube.com/watch?v=V-sEwsca1ak&t=185s

**Comment by gavinfish** [comment]
谢谢，已添加。
